  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Resume"
  weight = 300
  identifier = "resume"
  url = "/resume/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"