---
title: "Hello xportr!"
author: "Ben Straub"
date: 2022-01-07
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Hi everyone,

It's like a package a week that I get to announce!

We got another R package up on CRAN to help with the building of the clinical reporting pipeline using R. We call this pipeline the [pharmaverse](https://pharmaverse.org/).

Enter [xportr](https://atorus-research.github.io/xportr/)

A tool to help convert your R datasets into version 5 xpt files used for regulatory submission. We have a lot of custom checks to help get your datasets ready for conversion and validation. Let us know what you think! If you see pesky bugs or have ideas on improvements, please drop us an issue on GitHub.

Long term we are hoping that {xportr} can do more than just version 5 xpt files as the landscape of data types for submissions to regulatory agencies changes. Stay tuned!

Big shout out to Eli Miller from Atorus for helping to drive this effort. This was a joint effort between GSK and Atorus. One more package to round out the clinical reporting pipeline for R!

